name: Check Markdown links
# See https://github.com/UmbrellaDocs/linkspector

on:
  # push:
  schedule:
    # Runs at 08:00 UTC, on day 1 of each month.
    - cron: "0 8 1 * *"

  # Allow this workflow to be called from other repositories.
  workflow_call:

  # Allow this workflow to be called from the GitHub UI.
  workflow_dispatch:

jobs:
  markdown-link-check:
    runs-on: ubuntu-22.04
    if: github.event.pull_request.labels[0].name != 'no release notes'
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: 20
    - name: Install dependencies
      run: npm install -g @umbrelladocs/linkspector
    - name: Check links
      run: |
        # Generate default configuration file if it doesn't exist.
        # - github.com URL's can lead to rate limiting errors.
        # - stsci.edu URL's can lead to connection refused errors.
        if [ ! -f .linkspector.yml ] ; then printf "dirs:\n  - ./\nignorePatterns:\n  - pattern: '^https://www.gnu.org/licenses.*$'\n  - pattern: '^https://jwst-docs.stsci.edu/.*$'\n" > .linkspector.yml ; fi
        # Run the check.
        linkspector check
