name: Check Markdown links
# See https://github.com/UmbrellaDocs/linkspector

on:
  push:
  schedule:
    - # Run every day at 5:00 UTC
    - cron: "0 5 * * *"

  # Allow this workflow to be called from other repositories.
  workflow_call:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    if: github.event.pull_request.labels[0].name != 'no release notes'
    steps:
    - uses: actions/checkout@v4.2.2
    - uses: actions/setup-node@v4.1.0
      with:
        node-version: 20
    - name: Install dependencies
      run: npm install -g @umbrelladocs/linkspector
    - name: Check links
      run: |
        # Generate default configuration file if it doesn't exist.
        if [ ! -f .linkspector.yml ] ; then printf "dirs:\n  - ./\n" > .linkspector.yml ; fi
        # Run the check.
        linkspector check
