name: Check Markdown links

on:
  push:
  schedule:
    - # Run every day at 5:00 UTC
    - cron: "0 5 * * *"

  # Allow this workflow to be called from other repositories.
  workflow_call:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: |
        apt-get install npm
        # See https://github.com/UmbrellaDocs/linkspector
        npm install -g @umbrelladocs/linkspector
    - name: Check links
      run: |
        # Generate default configuration file if it doesn't exist.
        if [ ! -f .linkspector.yml ] ; then printf "dirs:\n  - ./\n" > .linkspector.yml ; fi
        # Run the check.
        linkspector check
