name: Check Markdown links

on:
  push:
  schedule:
    - # Run every day at 5:00 UTC
    - cron: "0 5 * * *"

  # Allow this workflow to be called from other repositories.
  workflow_call:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: |
        apt-get install npm
        npm install -g @umbrelladocs/linkspector
    - name: Check links
      run: |
        printf "dirs:\n  - ./\n" > .linkspector.yml
        linkspector check