name: Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allow this workflow to be called from other repositories.
  workflow_call:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/AstarVienna/ScopeSim_Data.git
          # Install this clone of the project. This is relevant because for
          # example ScopeSim has ScopeSim_Templates as a test-dependency
          # and that package has ScopeSim as a dependency. So the PyPI version
          # of ScopeSim would be installed without the "pip install ." line.
          pip install .
          # TODO: It should not be necessary to install the dev dependencies.
          #       Perhaps create a separate test for that?
          pip install .[test,dev]
          pip install pytest pytest-cov
      - name: Run Pytest
        run: pytest --cov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
