name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allow this workflow to be called from other repositories.
  workflow_call:
    inputs:
      poetry:
        type: boolean
        description: "Deprecated, will now always use Poetry."
        required: false
        default: true

jobs:
  run-tests:
    name: ${{ matrix.experimental && '⚠️ Experimental: ' || '' }}${{ matrix.os }}, ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12']
        experimental: [false]
        include:
          - os: ubuntu-latest
            python-version: '3.9'
            experimental: true
          - os: macos-latest
            python-version: '3.9'
            experimental: true
          - os: windows-latest
            python-version: '3.9'
            experimental: true

    steps:
      - uses: actions/checkout@v5

      - name: Install poetry
        shell: bash
        run: pipx install poetry==2.1.4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies with Poetry
        continue-on-error: ${{ matrix.experimental }}
        run: |
          poetry install --with test --all-extras
          poetry add git+https://github.com/AstarVienna/ScopeSim_Data.git
          poetry env use "$(python -c 'import sys; print(sys.executable)')"

      - name: Check Python version
        run: poetry run python -V >> "$GITHUB_STEP_SUMMARY"

      - name: Run Pytest with Poetry
        continue-on-error: ${{ matrix.experimental }}
        run: poetry run pytest -m "not webtest" --cov --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
