name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allow this workflow to be called from other repositories.
  workflow_call:

# This workflow need Poetry, so no flag is included.

jobs:
  run-tests:
    name: ${{ matrix.os }}, ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.12']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "2.1.3"

      - name: Install dependencies
        shell: bash
        run: |
          poetry lock
          poetry install --with test --all-extras
          poetry add git+https://github.com/AstarVienna/ScopeSim_Data.git

      - name: Update dependencies
        shell: bash
        run: poetry update | tee -a $GITHUB_STEP_SUMMARY

      - name: Run Pytest
        shell: bash
        run: poetry run pytest -m "not webtest" --cov --cov-report=xml

  call-tests:
    name: Offline tests with poetry
    uses: ./.github/workflows/tests.yml
    with:
      poetry: True
    secrets: inherit

  call-tests:
    name: Offline tests without poetry
    uses: ./.github/workflows/tests.yml
    with:
      poetry: False
    secrets: inherit
