name: Webtests
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allow this workflow to be called from other repositories.
  workflow_call:
    inputs:
      poetry:
        type: boolean
        description: "Deprecated, will now always use Poetry."
        required: false

jobs:
  run-tests:
    # The web tests are run with a limited matrix, because they retrieve data
    #  from the internet and therefor run into rate limits with the full matrix.
    name: ${{ matrix.experimental && '⚠️ ' || '' }}ubuntu-latest, ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.12', '3.13']
        experimental: [false]
        include:
          - os: ubuntu-latest
            python-version: '3.14'
            experimental: true

    steps:
      - uses: actions/checkout@v5

      - name: Install poetry
        shell: bash
        run: pipx install poetry==2.1.4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies with Poetry
        continue-on-error: ${{ matrix.experimental }}
        run: |
          poetry install --with test --all-extras
          poetry add git+https://github.com/AstarVienna/ScopeSim_Data.git
          poetry env use "$(python -c 'import sys; print(sys.executable)')"

      - name: Check Python version
        run: poetry run python -V >> "$GITHUB_STEP_SUMMARY"

      - name: Run Pytest with Poetry
        continue-on-error: ${{ matrix.experimental }}
        run: poetry run pytest -m "webtest" --cov --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
